name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.0
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  go_router: ^13.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image.png
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/domitory1.jpeg
    - assets/domitory2.jpeg
    - assets/domitory3.jpeg
    - assets/fee.jpg